### ISSUE TITLE
Option to remove @ on summary

### ISSUE THREAD

**Issue by phiet-do-mc** [bradleyboy/standbot#21]
Is there a way we can make it optional to @/mention users in the summary? I was thinking of making a `summaryUser` variable in which it would just return ``<${userId}>``

https://github.com/bradleyboy/standbot/blob/68c32a3bb4a60ee1d6af56d7cd218d12d3fad29f/actions/index.js#L125

**Comment by bradleyboy** [comment]
@phiet-do-mc there isn't a way to do this now, but it probably doesn't need to at-mention the users at all when dumping out the summary. I'd be fine just removing that from the summary altogether if you were open to PR-ing the change!

**Comment by phiet-do-mc** [comment]
I'm definitely open to PR-ing the change! It would be quick and simple I'm hoping

**Comment by phiet-do-mc** [comment]
pr is up: https://github.com/bradleyboy/standbot/pull/22

**Comment by bradleyboy** [comment]
fixed in https://github.com/bradleyboy/standbot/pull/22 thanks!
